--
-- America Ships On Click — Data
--
-- Rows only: demo accounts, loads, bookings, settlements, and platform config. Load database/sql/schema.sql first.
--
-- Generated by database/scripts/export-sql.sh from a live database.
-- Target: PostgreSQL 12+
--
-- Load with:
--   psql "$DATABASE_URL" -f database/sql/data.sql
--
-- Or paste into any SQL console (Supabase, pgAdmin, Neon, RDS Query Editor).
--

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: api_rate_limits; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: audit_log; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (1, 'bookings', 'INSERT', 'BK-QZ_5yJ-UL8Gj', 'usr-driver-1', 'driver', NULL, '{"id": "BK-QZ_5yJ-UL8Gj", "status": "active", "load_id": "LD-1043", "pod_url": null, "booked_at": "2026-09-09T20:43:04.973634+05:45", "driver_id": "drv-001", "delivered_at": null}', '2026-09-09 20:43:04.973634+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (2, 'loads', 'UPDATE', 'LD-1043', 'usr-driver-1', 'driver', '{"id": "LD-1043", "miles": 530, "notes": "Continuous temp 34F", "status": "open", "dest_city": "Memphis", "created_at": "2026-09-09T18:30:16.595462+05:45", "dest_state": "TN", "shipper_id": "shp-001", "weight_lbs": 38200, "origin_city": "Chicago", "pickup_date": "2026-08-03", "origin_state": "IL", "rate_per_mile": 2.45, "equipment_type": "reefer", "same_day_funding_offered": true}', '{"id": "LD-1043", "miles": 530, "notes": "Continuous temp 34F", "status": "booked", "dest_city": "Memphis", "created_at": "2026-09-09T18:30:16.595462+05:45", "dest_state": "TN", "shipper_id": "shp-001", "weight_lbs": 38200, "origin_city": "Chicago", "pickup_date": "2026-08-03", "origin_state": "IL", "rate_per_mile": 2.45, "equipment_type": "reefer", "same_day_funding_offered": true}', '2026-09-09 20:43:04.973634+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (3, 'bookings', 'UPDATE', 'BK-QZ_5yJ-UL8Gj', 'usr-driver-1', 'driver', '{"id": "BK-QZ_5yJ-UL8Gj", "status": "active", "load_id": "LD-1043", "pod_url": null, "booked_at": "2026-09-09T20:43:04.973634+05:45", "driver_id": "drv-001", "delivered_at": null}', '{"id": "BK-QZ_5yJ-UL8Gj", "status": "active", "load_id": "LD-1043", "pod_url": "/uploads/pod.png", "booked_at": "2026-09-09T20:43:04.973634+05:45", "driver_id": "drv-001", "delivered_at": null}', '2026-09-09 20:43:05.038318+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (4, 'settlements', 'INSERT', 'STL-n1lovcowNFQ6', 'usr-driver-1', 'driver', NULL, '{"id": "STL-n1lovcowNFQ6", "miles": 530, "load_id": "LD-1043", "factored": true, "fuel_cost": 238.5, "booking_id": "BK-QZ_5yJ-UL8Gj", "fee_amount": 64.925, "net_amount": 956.12, "settled_at": "2026-09-09T20:43:05.051+05:45", "factor_cost": 38.955, "gross_amount": 1298.5, "rate_per_mile": 2.45, "fee_pct_applied": 0.05, "fuel_rate_per_mile": 0.45}', '2026-09-09 20:43:05.048649+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (5, 'bookings', 'UPDATE', 'BK-QZ_5yJ-UL8Gj', 'usr-driver-1', 'driver', '{"id": "BK-QZ_5yJ-UL8Gj", "status": "active", "load_id": "LD-1043", "pod_url": "/uploads/pod.png", "booked_at": "2026-09-09T20:43:04.973634+05:45", "driver_id": "drv-001", "delivered_at": null}', '{"id": "BK-QZ_5yJ-UL8Gj", "status": "completed", "load_id": "LD-1043", "pod_url": "/uploads/pod.png", "booked_at": "2026-09-09T20:43:04.973634+05:45", "driver_id": "drv-001", "delivered_at": "2026-09-09T20:43:05.051+05:45"}', '2026-09-09 20:43:05.048649+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (6, 'loads', 'UPDATE', 'LD-1043', 'usr-driver-1', 'driver', '{"id": "LD-1043", "miles": 530, "notes": "Continuous temp 34F", "status": "booked", "dest_city": "Memphis", "created_at": "2026-09-09T18:30:16.595462+05:45", "dest_state": "TN", "shipper_id": "shp-001", "weight_lbs": 38200, "origin_city": "Chicago", "pickup_date": "2026-08-03", "origin_state": "IL", "rate_per_mile": 2.45, "equipment_type": "reefer", "same_day_funding_offered": true}', '{"id": "LD-1043", "miles": 530, "notes": "Continuous temp 34F", "status": "delivered", "dest_city": "Memphis", "created_at": "2026-09-09T18:30:16.595462+05:45", "dest_state": "TN", "shipper_id": "shp-001", "weight_lbs": 38200, "origin_city": "Chicago", "pickup_date": "2026-08-03", "origin_state": "IL", "rate_per_mile": 2.45, "equipment_type": "reefer", "same_day_funding_offered": true}', '2026-09-09 20:43:05.048649+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (7, 'users', 'INSERT', 'usr-qJ705CJD_XXZ', NULL, 'enrollment', NULL, '{"id": "usr-qJ705CJD_XXZ", "role": "shipper", "email": "newshipper@test.com", "phone": null, "created_at": "2026-09-09T20:43:24.94798+05:45", "updated_at": "2026-09-09T20:43:24.94798+05:45"}', '2026-09-09 20:43:24.94798+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (8, 'loads', 'INSERT', 'LD-_24IiSviJStv', 'usr-qJ705CJD_XXZ', 'shipper', NULL, '{"id": "LD-_24IiSviJStv", "miles": 420, "notes": null, "status": "open", "dest_city": "Boise", "created_at": "2026-09-09T20:43:25.053941+05:45", "dest_state": "ID", "shipper_id": "shp-hxYmLCYf7JpK", "weight_lbs": null, "origin_city": "Reno", "pickup_date": "2026-09-20", "origin_state": "NV", "rate_per_mile": 2.6, "equipment_type": "dry_van", "same_day_funding_offered": false}', '2026-09-09 20:43:25.053941+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (9, 'users', 'INSERT', 'usr-UBVnwhupvrVL', NULL, 'enrollment', NULL, '{"id": "usr-UBVnwhupvrVL", "role": "driver", "email": "sectest@test.com", "phone": "15550002222", "created_at": "2026-09-09T20:43:25.134065+05:45", "updated_at": "2026-09-09T20:43:25.134065+05:45"}', '2026-09-09 20:43:25.134065+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (10, 'driver_payment_accounts', 'INSERT', 'pay-drv-wI2aqzVEQH-x', NULL, 'enrollment', NULL, '{"id": "pay-drv-wI2aqzVEQH-x", "driver_id": "drv-wI2aqzVEQH-x", "created_at": "2026-09-09T20:43:25.134065+05:45", "payment_processor": "stripe_connect", "same_day_funding_opt_in": true}', '2026-09-09 20:43:25.134065+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (11, 'bookings', 'INSERT', 'BK-VVjRBu-MiV8K', 'usr-driver-2', 'driver', NULL, '{"id": "BK-VVjRBu-MiV8K", "status": "active", "load_id": "LD-1044", "pod_url": null, "booked_at": "2026-09-09T20:44:02.05395+05:45", "driver_id": "drv-002", "delivered_at": null}', '2026-09-09 20:44:02.05395+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (12, 'loads', 'UPDATE', 'LD-1044', 'usr-driver-2', 'driver', '{"id": "LD-1044", "miles": 370, "notes": "Straps and tarp required", "status": "open", "dest_city": "Phoenix", "created_at": "2026-09-09T18:30:16.595462+05:45", "dest_state": "AZ", "shipper_id": "shp-001", "weight_lbs": 44000, "origin_city": "Los Angeles", "pickup_date": "2026-08-05", "origin_state": "CA", "rate_per_mile": 2.9, "equipment_type": "flatbed", "same_day_funding_offered": true}', '{"id": "LD-1044", "miles": 370, "notes": "Straps and tarp required", "status": "booked", "dest_city": "Phoenix", "created_at": "2026-09-09T18:30:16.595462+05:45", "dest_state": "AZ", "shipper_id": "shp-001", "weight_lbs": 44000, "origin_city": "Los Angeles", "pickup_date": "2026-08-05", "origin_state": "CA", "rate_per_mile": 2.9, "equipment_type": "flatbed", "same_day_funding_offered": true}', '2026-09-09 20:44:02.05395+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (13, 'bookings', 'INSERT', 'BK-9Xj5sNlMwJmw', 'usr-driver-2', 'driver', NULL, '{"id": "BK-9Xj5sNlMwJmw", "status": "active", "load_id": "LD-1045", "pod_url": null, "booked_at": "2026-09-09T20:44:41.275833+05:45", "driver_id": "drv-002", "delivered_at": null}', '2026-09-09 20:44:41.275833+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (14, 'loads', 'UPDATE', 'LD-1045', 'usr-driver-2', 'driver', '{"id": "LD-1045", "miles": 1240, "notes": "Clean trailer required", "status": "open", "dest_city": "Chicago", "created_at": "2026-09-09T18:30:16.595462+05:45", "dest_state": "IL", "shipper_id": "shp-001", "weight_lbs": 40000, "origin_city": "Laredo", "pickup_date": "2026-08-06", "origin_state": "TX", "rate_per_mile": 2.2, "equipment_type": "dry_van", "same_day_funding_offered": true}', '{"id": "LD-1045", "miles": 1240, "notes": "Clean trailer required", "status": "booked", "dest_city": "Chicago", "created_at": "2026-09-09T18:30:16.595462+05:45", "dest_state": "IL", "shipper_id": "shp-001", "weight_lbs": 40000, "origin_city": "Laredo", "pickup_date": "2026-08-06", "origin_state": "TX", "rate_per_mile": 2.2, "equipment_type": "dry_van", "same_day_funding_offered": true}', '2026-09-09 20:44:41.275833+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (15, 'users', 'INSERT', 'usr-TUkIkFbOg6pG', NULL, 'enrollment', NULL, '{"id": "usr-TUkIkFbOg6pG", "role": "driver", "email": "victim.14873@trucking.com", "phone": null, "created_at": "2026-09-10T08:31:15.269492+05:45", "updated_at": "2026-09-10T08:31:15.269492+05:45"}', '2026-09-10 08:31:15.269492+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (16, 'driver_payment_accounts', 'INSERT', 'pay-drv-E3c4Jcvw0Ygw', NULL, 'enrollment', NULL, '{"id": "pay-drv-E3c4Jcvw0Ygw", "driver_id": "drv-E3c4Jcvw0Ygw", "created_at": "2026-09-10T08:31:15.269492+05:45", "payment_processor": "stripe_connect", "same_day_funding_opt_in": true}', '2026-09-10 08:31:15.269492+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (17, 'users', 'INSERT', 'usr-JU2XzwDN3L0J', NULL, 'enrollment', NULL, '{"id": "usr-JU2XzwDN3L0J", "role": "driver", "email": "victim.20226@trucking.com", "phone": null, "created_at": "2026-09-10T08:31:30.300483+05:45", "updated_at": "2026-09-10T08:31:30.300483+05:45"}', '2026-09-10 08:31:30.300483+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (18, 'driver_payment_accounts', 'INSERT', 'pay-drv-y-6Ted4ji-4G', NULL, 'enrollment', NULL, '{"id": "pay-drv-y-6Ted4ji-4G", "driver_id": "drv-y-6Ted4ji-4G", "created_at": "2026-09-10T08:31:30.300483+05:45", "payment_processor": "stripe_connect", "same_day_funding_opt_in": true}', '2026-09-10 08:31:30.300483+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (19, 'driver_payment_accounts', 'UPDATE', 'pay-drv-y-6Ted4ji-4G', 'usr-JU2XzwDN3L0J', 'driver', '{"id": "pay-drv-y-6Ted4ji-4G", "driver_id": "drv-y-6Ted4ji-4G", "created_at": "2026-09-10T08:31:30.300483+05:45", "payment_processor": "stripe_connect", "same_day_funding_opt_in": true}', '{"id": "pay-drv-y-6Ted4ji-4G", "driver_id": "drv-y-6Ted4ji-4G", "created_at": "2026-09-10T08:31:30.300483+05:45", "payment_processor": "stripe_connect", "same_day_funding_opt_in": true}', '2026-09-10 08:32:56.368938+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (20, 'users', 'INSERT', 'usr-YVkHDl4yaIK7', NULL, 'enrollment', NULL, '{"id": "usr-YVkHDl4yaIK7", "role": "driver", "email": "attacker.32159@evil.com", "phone": null, "created_at": "2026-09-10T08:33:11.987873+05:45", "updated_at": "2026-09-10T08:33:11.987873+05:45"}', '2026-09-10 08:33:11.987873+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (21, 'driver_payment_accounts', 'INSERT', 'pay-drv-dgfO2s6by-3q', NULL, 'enrollment', NULL, '{"id": "pay-drv-dgfO2s6by-3q", "driver_id": "drv-dgfO2s6by-3q", "created_at": "2026-09-10T08:33:11.987873+05:45", "payment_processor": "stripe_connect", "same_day_funding_opt_in": true}', '2026-09-10 08:33:11.987873+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (22, 'driver_payment_accounts', 'UPDATE', 'pay-drv-dgfO2s6by-3q', 'usr-YVkHDl4yaIK7', 'driver', '{"id": "pay-drv-dgfO2s6by-3q", "driver_id": "drv-dgfO2s6by-3q", "created_at": "2026-09-10T08:33:11.987873+05:45", "payment_processor": "stripe_connect", "same_day_funding_opt_in": true}', '{"id": "pay-drv-dgfO2s6by-3q", "driver_id": "drv-dgfO2s6by-3q", "created_at": "2026-09-10T08:33:11.987873+05:45", "payment_processor": "stripe_connect", "same_day_funding_opt_in": true}', '2026-09-10 08:33:12.027311+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (23, 'platform_config', 'INSERT', 'require_driver_verification', NULL, 'anon', NULL, '{"key": "require_driver_verification", "value": 0, "updated_at": "2026-09-10T13:37:28.255315+05:45"}', '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (24, 'users', 'INSERT', 'usr-p8-PrQ1v1Oag', NULL, 'enrollment', NULL, '{"id": "usr-p8-PrQ1v1Oag", "role": "driver", "email": "gate-driver@test.com", "phone": null, "created_at": "2026-09-10T14:03:25.166416+05:45", "updated_at": "2026-09-10T14:03:25.166416+05:45"}', '2026-09-10 14:03:25.166416+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (25, 'driver_payment_accounts', 'INSERT', 'pay-drv-jAfiA4K-lTUV', NULL, 'enrollment', NULL, '{"id": "pay-drv-jAfiA4K-lTUV", "driver_id": "drv-jAfiA4K-lTUV", "created_at": "2026-09-10T14:03:25.166416+05:45", "payment_processor": "stripe_connect", "same_day_funding_opt_in": true}', '2026-09-10 14:03:25.166416+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (26, 'users', 'INSERT', 'usr-j-3cQgErZfV_', NULL, 'enrollment', NULL, '{"id": "usr-j-3cQgErZfV_", "role": "shipper", "email": "gate-shipper@test.com", "phone": null, "created_at": "2026-09-10T14:03:53.007992+05:45", "updated_at": "2026-09-10T14:03:53.007992+05:45"}', '2026-09-10 14:03:53.007992+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (29, 'driver_payment_accounts', 'DELETE', 'pay-drv-jAfiA4K-lTUV', NULL, 'anon', '{"id": "pay-drv-jAfiA4K-lTUV", "driver_id": "drv-jAfiA4K-lTUV", "created_at": "2026-09-10T14:03:25.166416+05:45", "payment_processor": "stripe_connect", "same_day_funding_opt_in": true}', NULL, '2026-09-10 14:06:26.880252+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (30, 'users', 'DELETE', 'usr-p8-PrQ1v1Oag', NULL, 'anon', '{"id": "usr-p8-PrQ1v1Oag", "role": "driver", "email": "gate-driver@test.com", "phone": null, "created_at": "2026-09-10T14:03:25.166416+05:45", "updated_at": "2026-09-10T14:03:25.166416+05:45"}', NULL, '2026-09-10 14:06:26.880252+05:45');
INSERT INTO public.audit_log (id, table_name, operation, row_id, actor_id, actor_role, old_data, new_data, changed_at) VALUES (31, 'users', 'DELETE', 'usr-j-3cQgErZfV_', NULL, 'anon', '{"id": "usr-j-3cQgErZfV_", "role": "shipper", "email": "gate-shipper@test.com", "phone": null, "created_at": "2026-09-10T14:03:53.007992+05:45", "updated_at": "2026-09-10T14:03:53.007992+05:45"}', NULL, '2026-09-10 14:06:26.880252+05:45');


--
-- Data for Name: auth_login_attempts; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.auth_login_attempts (id, email, ip_address, succeeded, attempted_at) VALUES (1, 'john.smith@trucking.com', '127.0.0.1', true, '2026-09-09 20:41:43.033978+05:45');
INSERT INTO public.auth_login_attempts (id, email, ip_address, succeeded, attempted_at) VALUES (2, 'john.smith@trucking.com', '127.0.0.1', true, '2026-09-09 20:42:31.712619+05:45');
INSERT INTO public.auth_login_attempts (id, email, ip_address, succeeded, attempted_at) VALUES (3, 'maria.garcia@expedited.com', '127.0.0.1', true, '2026-09-09 20:42:31.801156+05:45');
INSERT INTO public.auth_login_attempts (id, email, ip_address, succeeded, attempted_at) VALUES (4, 'admin@americashipsonclick.com', '127.0.0.1', true, '2026-09-09 20:42:31.884802+05:45');
INSERT INTO public.auth_login_attempts (id, email, ip_address, succeeded, attempted_at) VALUES (5, 'newshipper@test.com', '127.0.0.1', true, '2026-09-09 20:43:25.036142+05:45');
INSERT INTO public.auth_login_attempts (id, email, ip_address, succeeded, attempted_at) VALUES (11, 'john.smith@trucking.com', '127.0.0.1', true, '2026-09-09 20:47:11.379526+05:45');
INSERT INTO public.auth_login_attempts (id, email, ip_address, succeeded, attempted_at) VALUES (12, 'victim.14873@trucking.com', '127.0.0.1', false, '2026-09-10 08:31:15.510488+05:45');
INSERT INTO public.auth_login_attempts (id, email, ip_address, succeeded, attempted_at) VALUES (15, 'victim.20226@trucking.com', '127.0.0.1', true, '2026-09-10 08:31:45.90322+05:45');
INSERT INTO public.auth_login_attempts (id, email, ip_address, succeeded, attempted_at) VALUES (16, 'admin@americashipsonclick.com', '127.0.0.1', true, '2026-09-10 13:59:26.253836+05:45');
INSERT INTO public.auth_login_attempts (id, email, ip_address, succeeded, attempted_at) VALUES (17, 'admin@americashipsonclick.com', '127.0.0.1', true, '2026-09-10 13:59:43.216426+05:45');
INSERT INTO public.auth_login_attempts (id, email, ip_address, succeeded, attempted_at) VALUES (18, 'logistics@apexlogistics.com', '127.0.0.1', true, '2026-09-10 13:59:51.364912+05:45');
INSERT INTO public.auth_login_attempts (id, email, ip_address, succeeded, attempted_at) VALUES (19, 'john.smith@trucking.com', '127.0.0.1', true, '2026-09-10 14:00:03.224904+05:45');


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.users (id, role, email, phone, password_hash, created_at, updated_at) VALUES ('usr-admin-1', 'admin', 'admin@americashipsonclick.com', '18005550100', '$2b$10$kLe7ME.dVSU008RiJ.UyZuL.0krfSvICOMvGrNxH8pyEukV9Tu9DO', '2026-09-09 18:30:16.595462+05:45', '2026-09-09 18:30:16.595462+05:45');
INSERT INTO public.users (id, role, email, phone, password_hash, created_at, updated_at) VALUES ('usr-shipper-1', 'shipper', 'logistics@apexlogistics.com', '18005550199', '$2b$10$kLe7ME.dVSU008RiJ.UyZuL.0krfSvICOMvGrNxH8pyEukV9Tu9DO', '2026-09-09 18:30:16.595462+05:45', '2026-09-09 18:30:16.595462+05:45');
INSERT INTO public.users (id, role, email, phone, password_hash, created_at, updated_at) VALUES ('usr-driver-1', 'driver', 'john.smith@trucking.com', '18005550122', '$2b$10$kLe7ME.dVSU008RiJ.UyZuL.0krfSvICOMvGrNxH8pyEukV9Tu9DO', '2026-09-09 18:30:16.595462+05:45', '2026-09-09 18:30:16.595462+05:45');
INSERT INTO public.users (id, role, email, phone, password_hash, created_at, updated_at) VALUES ('usr-driver-2', 'driver', 'maria.garcia@expedited.com', '18005550122', '$2b$10$kLe7ME.dVSU008RiJ.UyZuL.0krfSvICOMvGrNxH8pyEukV9Tu9DO', '2026-09-09 18:30:16.595462+05:45', '2026-09-09 18:30:16.595462+05:45');
INSERT INTO public.users (id, role, email, phone, password_hash, created_at, updated_at) VALUES ('usr-qJ705CJD_XXZ', 'shipper', 'newshipper@test.com', NULL, '$2b$10$wW4L9RQRWjFriAzOxp6BhuG0B4baA/RgfrqVJhEkOBdJc6xZAC.ya', '2026-09-09 20:43:24.94798+05:45', '2026-09-09 20:43:24.94798+05:45');
INSERT INTO public.users (id, role, email, phone, password_hash, created_at, updated_at) VALUES ('usr-UBVnwhupvrVL', 'driver', 'sectest@test.com', '15550002222', '$2b$10$5iAsvC6WSJkXIRz1dZr16.bnoGQO9KF1BNZzydYcCpaRzZepZpvGi', '2026-09-09 20:43:25.134065+05:45', '2026-09-09 20:43:25.134065+05:45');
INSERT INTO public.users (id, role, email, phone, password_hash, created_at, updated_at) VALUES ('usr-TUkIkFbOg6pG', 'driver', 'victim.14873@trucking.com', NULL, '$2b$10$T00nO/e3DHZJlw0Gjx2lv.v/PbHuIHOOt9csuixH24fUtH6xDpiaG', '2026-09-10 08:31:15.269492+05:45', '2026-09-10 08:31:15.269492+05:45');
INSERT INTO public.users (id, role, email, phone, password_hash, created_at, updated_at) VALUES ('usr-JU2XzwDN3L0J', 'driver', 'victim.20226@trucking.com', NULL, '$2b$10$UCgl.P0j6Nfq7fXHBCMJd.6ZmS4KmaquiRKcHid1aC6nYUu8jWbIC', '2026-09-10 08:31:30.300483+05:45', '2026-09-10 08:31:30.300483+05:45');
INSERT INTO public.users (id, role, email, phone, password_hash, created_at, updated_at) VALUES ('usr-YVkHDl4yaIK7', 'driver', 'attacker.32159@evil.com', NULL, '$2b$10$OO2dFmu7dOMI2afiXX9LouEJhSQ/RMmGugNOkl0.qfvzELO/F7uhG', '2026-09-10 08:33:11.987873+05:45', '2026-09-10 08:33:11.987873+05:45');


--
-- Data for Name: driver_profiles; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.driver_profiles (id, user_id, full_name, home_base_city, home_base_state, cdl_number, cdl_class, dot_number, mc_number, verification_status, created_at, verified_at, verified_by, rejection_reason, insurance_expires_at) VALUES ('drv-001', 'usr-driver-1', 'John Smith', 'Joplin', 'MO', 'CDL-998811', 'A', 'DOT-33211', 'MC-77112', 'verified', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL);
INSERT INTO public.driver_profiles (id, user_id, full_name, home_base_city, home_base_state, cdl_number, cdl_class, dot_number, mc_number, verification_status, created_at, verified_at, verified_by, rejection_reason, insurance_expires_at) VALUES ('drv-002', 'usr-driver-2', 'Maria Garcia', 'Dallas', 'TX', 'CDL-441199', 'A', 'DOT-88123', 'MC-55991', 'verified', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL);
INSERT INTO public.driver_profiles (id, user_id, full_name, home_base_city, home_base_state, cdl_number, cdl_class, dot_number, mc_number, verification_status, created_at, verified_at, verified_by, rejection_reason, insurance_expires_at) VALUES ('drv-wI2aqzVEQH-x', 'usr-UBVnwhupvrVL', 'Sec Test', 'Ogden', 'UT', NULL, 'A', NULL, NULL, 'pending', '2026-09-09 20:43:25.134065+05:45', NULL, NULL, NULL, NULL);
INSERT INTO public.driver_profiles (id, user_id, full_name, home_base_city, home_base_state, cdl_number, cdl_class, dot_number, mc_number, verification_status, created_at, verified_at, verified_by, rejection_reason, insurance_expires_at) VALUES ('drv-E3c4Jcvw0Ygw', 'usr-TUkIkFbOg6pG', 'Victim Driver', 'Dallas', 'TX', NULL, 'A', NULL, NULL, 'verified', '2026-09-10 08:31:15.269492+05:45', NULL, NULL, NULL, NULL);
INSERT INTO public.driver_profiles (id, user_id, full_name, home_base_city, home_base_state, cdl_number, cdl_class, dot_number, mc_number, verification_status, created_at, verified_at, verified_by, rejection_reason, insurance_expires_at) VALUES ('drv-y-6Ted4ji-4G', 'usr-JU2XzwDN3L0J', 'Victim Driver', 'Joplin', 'MO', 'CDL9911', 'A', '1234567', 'MC7788', 'verified', '2026-09-10 08:31:30.300483+05:45', NULL, NULL, NULL, NULL);
INSERT INTO public.driver_profiles (id, user_id, full_name, home_base_city, home_base_state, cdl_number, cdl_class, dot_number, mc_number, verification_status, created_at, verified_at, verified_by, rejection_reason, insurance_expires_at) VALUES ('drv-dgfO2s6by-3q', 'usr-YVkHDl4yaIK7', 'Attacker', 'X', 'TX', NULL, 'A', NULL, NULL, 'verified', '2026-09-10 08:33:11.987873+05:45', NULL, NULL, NULL, NULL);


--
-- Data for Name: shipper_profiles; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.shipper_profiles (id, user_id, company_name, billing_email, created_at) VALUES ('shp-001', 'usr-shipper-1', 'Apex Freight Corp', 'billing@apexlogistics.com', '2026-09-09 18:30:16.595462+05:45');
INSERT INTO public.shipper_profiles (id, user_id, company_name, billing_email, created_at) VALUES ('shp-hxYmLCYf7JpK', 'usr-qJ705CJD_XXZ', 'New Shipper Co', 'newshipper@test.com', '2026-09-09 20:43:24.94798+05:45');


--
-- Data for Name: loads; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-1042', 'shp-001', 'Dallas', 'TX', 'Atlanta', 'GA', 780, 2.15, 'dry_van', '2026-08-04', 41900, '26 pallets non-hazmat', true, 'open', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-1046', 'shp-001', 'Charlotte', 'NC', 'Miami', 'FL', 650, 2.35, 'reefer', '2026-08-04', 36500, 'Pre-cooled to 36F', true, 'open', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-1047', 'shp-001', 'Columbus', 'OH', 'Newark', 'NJ', 530, 2.6, 'step_deck', '2026-08-07', 42800, 'Overheight machinery', true, 'open', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-1048', 'shp-001', 'Seattle', 'WA', 'Denver', 'CO', 1020, 2.3, 'dry_van', '2026-08-05', 39600, 'No hazmat', true, 'open', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-1049', 'shp-001', 'Houston', 'TX', 'Nashville', 'TN', 780, 2.5, 'flatbed', '2026-08-06', 45000, 'Steel coils', true, 'open', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-1050', 'shp-001', 'Indianapolis', 'IN', 'Kansas City', 'MO', 490, 2.75, 'power_only', '2026-08-03', 0, 'Pre-loaded trailer drop', true, 'open', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-1051', 'shp-001', 'Savannah', 'GA', 'Charlotte', 'NC', 260, 3.05, 'dry_van', '2026-08-04', 37100, 'Port pickup', true, 'open', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-1052', 'shp-001', 'Ontario', 'CA', 'Salt Lake City', 'UT', 700, 2.2, 'reefer', '2026-08-08', 40900, 'Frozen food -10F', true, 'open', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-1053', 'shp-001', 'Harrisburg', 'PA', 'Boston', 'MA', 370, 2.65, 'dry_van', '2026-08-05', 41200, 'Live load', true, 'open', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-HIST-0001', 'shp-001', 'Dallas', 'TX', 'Atlanta', 'GA', 780, 2.42, 'dry_van', '2026-07-20', NULL, NULL, false, 'delivered', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-HIST-0002', 'shp-001', 'Chicago', 'IL', 'Memphis', 'TN', 530, 2.09, 'reefer', '2026-07-20', NULL, NULL, false, 'delivered', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-HIST-0003', 'shp-001', 'Los Angeles', 'CA', 'Phoenix', 'AZ', 370, 2.91, 'flatbed', '2026-07-20', NULL, NULL, false, 'delivered', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-HIST-0004', 'shp-001', 'Laredo', 'TX', 'Chicago', 'IL', 1240, 2.74, 'dry_van', '2026-07-20', NULL, NULL, false, 'delivered', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-HIST-0005', 'shp-001', 'Charlotte', 'NC', 'Miami', 'FL', 650, 2.25, 'reefer', '2026-07-20', NULL, NULL, false, 'delivered', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-HIST-0006', 'shp-001', 'Columbus', 'OH', 'Newark', 'NJ', 530, 2.85, 'step_deck', '2026-07-20', NULL, NULL, false, 'delivered', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-HIST-0007', 'shp-001', 'Seattle', 'WA', 'Denver', 'CO', 1020, 2.63, 'dry_van', '2026-07-20', NULL, NULL, false, 'delivered', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-HIST-0008', 'shp-001', 'Houston', 'TX', 'Nashville', 'TN', 780, 3.11, 'flatbed', '2026-07-20', NULL, NULL, false, 'delivered', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-HIST-0009', 'shp-001', 'Indianapolis', 'IN', 'Kansas City', 'MO', 490, 2.48, 'power_only', '2026-07-20', NULL, NULL, false, 'delivered', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-HIST-0010', 'shp-001', 'Savannah', 'GA', 'Charlotte', 'NC', 260, 3.14, 'dry_van', '2026-07-20', NULL, NULL, false, 'delivered', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-HIST-0011', 'shp-001', 'Ontario', 'CA', 'Salt Lake City', 'UT', 700, 2.19, 'reefer', '2026-07-20', NULL, NULL, false, 'delivered', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-HIST-0012', 'shp-001', 'Harrisburg', 'PA', 'Boston', 'MA', 370, 2.08, 'dry_van', '2026-07-20', NULL, NULL, false, 'delivered', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-HIST-0013', 'shp-001', 'Dallas', 'TX', 'Atlanta', 'GA', 780, 3.08, 'dry_van', '2026-07-20', NULL, NULL, false, 'delivered', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-HIST-0014', 'shp-001', 'Chicago', 'IL', 'Memphis', 'TN', 530, 2.78, 'reefer', '2026-07-20', NULL, NULL, false, 'delivered', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-HIST-0015', 'shp-001', 'Los Angeles', 'CA', 'Phoenix', 'AZ', 370, 2.68, 'flatbed', '2026-07-20', NULL, NULL, false, 'delivered', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-HIST-0016', 'shp-001', 'Laredo', 'TX', 'Chicago', 'IL', 1240, 2.6, 'dry_van', '2026-07-20', NULL, NULL, false, 'delivered', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-HIST-0017', 'shp-001', 'Charlotte', 'NC', 'Miami', 'FL', 650, 2.49, 'reefer', '2026-07-20', NULL, NULL, false, 'delivered', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-HIST-0018', 'shp-001', 'Columbus', 'OH', 'Newark', 'NJ', 530, 2.39, 'step_deck', '2026-07-20', NULL, NULL, false, 'delivered', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-1043', 'shp-001', 'Chicago', 'IL', 'Memphis', 'TN', 530, 2.45, 'reefer', '2026-08-03', 38200, 'Continuous temp 34F', true, 'delivered', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-_24IiSviJStv', 'shp-hxYmLCYf7JpK', 'Reno', 'NV', 'Boise', 'ID', 420, 2.6, 'dry_van', '2026-09-20', NULL, NULL, false, 'open', '2026-09-09 20:43:25.053941+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-1044', 'shp-001', 'Los Angeles', 'CA', 'Phoenix', 'AZ', 370, 2.9, 'flatbed', '2026-08-05', 44000, 'Straps and tarp required', true, 'booked', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.loads (id, shipper_id, origin_city, origin_state, dest_city, dest_state, miles, rate_per_mile, equipment_type, pickup_date, weight_lbs, notes, same_day_funding_offered, status, created_at, delivery_date, commodity, reference_number, cancelled_at, cancellation_reason, updated_at) VALUES ('LD-1045', 'shp-001', 'Laredo', 'TX', 'Chicago', 'IL', 1240, 2.2, 'dry_van', '2026-08-06', 40000, 'Clean trailer required', true, 'booked', '2026-09-09 18:30:16.595462+05:45', NULL, NULL, NULL, NULL, NULL, '2026-09-10 13:37:28.255315+05:45');


--
-- Data for Name: bookings; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.bookings (id, load_id, driver_id, booked_at, status, pod_url, delivered_at, picked_up_at, cancelled_at, cancellation_reason, cancelled_by, agreed_rate_per_mile) VALUES ('BK-HIST-0001', 'LD-HIST-0001', 'drv-001', '2026-09-09 18:30:16.595462+05:45', 'completed', NULL, '2026-09-01 05:52:31.524+05:45', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.bookings (id, load_id, driver_id, booked_at, status, pod_url, delivered_at, picked_up_at, cancelled_at, cancellation_reason, cancelled_by, agreed_rate_per_mile) VALUES ('BK-HIST-0002', 'LD-HIST-0002', 'drv-001', '2026-09-09 18:30:16.595462+05:45', 'completed', NULL, '2026-09-01 17:38:33.453+05:45', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.bookings (id, load_id, driver_id, booked_at, status, pod_url, delivered_at, picked_up_at, cancelled_at, cancellation_reason, cancelled_by, agreed_rate_per_mile) VALUES ('BK-HIST-0003', 'LD-HIST-0003', 'drv-001', '2026-09-09 18:30:16.595462+05:45', 'completed', NULL, '2026-09-02 05:48:28.146+05:45', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.bookings (id, load_id, driver_id, booked_at, status, pod_url, delivered_at, picked_up_at, cancelled_at, cancellation_reason, cancelled_by, agreed_rate_per_mile) VALUES ('BK-HIST-0004', 'LD-HIST-0004', 'drv-001', '2026-09-09 18:30:16.595462+05:45', 'completed', NULL, '2026-09-02 17:31:55.521+05:45', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.bookings (id, load_id, driver_id, booked_at, status, pod_url, delivered_at, picked_up_at, cancelled_at, cancellation_reason, cancelled_by, agreed_rate_per_mile) VALUES ('BK-HIST-0005', 'LD-HIST-0005', 'drv-001', '2026-09-09 18:30:16.595462+05:45', 'completed', NULL, '2026-09-03 05:39:46.822+05:45', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.bookings (id, load_id, driver_id, booked_at, status, pod_url, delivered_at, picked_up_at, cancelled_at, cancellation_reason, cancelled_by, agreed_rate_per_mile) VALUES ('BK-HIST-0006', 'LD-HIST-0006', 'drv-001', '2026-09-09 18:30:16.595462+05:45', 'completed', NULL, '2026-09-03 18:15:16.858+05:45', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.bookings (id, load_id, driver_id, booked_at, status, pod_url, delivered_at, picked_up_at, cancelled_at, cancellation_reason, cancelled_by, agreed_rate_per_mile) VALUES ('BK-HIST-0007', 'LD-HIST-0007', 'drv-001', '2026-09-09 18:30:16.595462+05:45', 'completed', NULL, '2026-09-04 06:02:34.778+05:45', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.bookings (id, load_id, driver_id, booked_at, status, pod_url, delivered_at, picked_up_at, cancelled_at, cancellation_reason, cancelled_by, agreed_rate_per_mile) VALUES ('BK-HIST-0008', 'LD-HIST-0008', 'drv-001', '2026-09-09 18:30:16.595462+05:45', 'completed', NULL, '2026-09-04 18:06:48.652+05:45', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.bookings (id, load_id, driver_id, booked_at, status, pod_url, delivered_at, picked_up_at, cancelled_at, cancellation_reason, cancelled_by, agreed_rate_per_mile) VALUES ('BK-HIST-0009', 'LD-HIST-0009', 'drv-001', '2026-09-09 18:30:16.595462+05:45', 'completed', NULL, '2026-09-05 05:30:49.889+05:45', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.bookings (id, load_id, driver_id, booked_at, status, pod_url, delivered_at, picked_up_at, cancelled_at, cancellation_reason, cancelled_by, agreed_rate_per_mile) VALUES ('BK-HIST-0010', 'LD-HIST-0010', 'drv-001', '2026-09-09 18:30:16.595462+05:45', 'completed', NULL, '2026-09-05 17:53:54.84+05:45', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.bookings (id, load_id, driver_id, booked_at, status, pod_url, delivered_at, picked_up_at, cancelled_at, cancellation_reason, cancelled_by, agreed_rate_per_mile) VALUES ('BK-HIST-0011', 'LD-HIST-0011', 'drv-001', '2026-09-09 18:30:16.595462+05:45', 'completed', NULL, '2026-09-06 05:33:42.363+05:45', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.bookings (id, load_id, driver_id, booked_at, status, pod_url, delivered_at, picked_up_at, cancelled_at, cancellation_reason, cancelled_by, agreed_rate_per_mile) VALUES ('BK-HIST-0012', 'LD-HIST-0012', 'drv-001', '2026-09-09 18:30:16.595462+05:45', 'completed', NULL, '2026-09-06 17:52:55.979+05:45', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.bookings (id, load_id, driver_id, booked_at, status, pod_url, delivered_at, picked_up_at, cancelled_at, cancellation_reason, cancelled_by, agreed_rate_per_mile) VALUES ('BK-HIST-0013', 'LD-HIST-0013', 'drv-001', '2026-09-09 18:30:16.595462+05:45', 'completed', NULL, '2026-09-07 05:31:06.74+05:45', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.bookings (id, load_id, driver_id, booked_at, status, pod_url, delivered_at, picked_up_at, cancelled_at, cancellation_reason, cancelled_by, agreed_rate_per_mile) VALUES ('BK-HIST-0014', 'LD-HIST-0014', 'drv-001', '2026-09-09 18:30:16.595462+05:45', 'completed', NULL, '2026-09-07 18:08:53.531+05:45', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.bookings (id, load_id, driver_id, booked_at, status, pod_url, delivered_at, picked_up_at, cancelled_at, cancellation_reason, cancelled_by, agreed_rate_per_mile) VALUES ('BK-HIST-0015', 'LD-HIST-0015', 'drv-001', '2026-09-09 18:30:16.595462+05:45', 'completed', NULL, '2026-09-08 05:49:03.159+05:45', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.bookings (id, load_id, driver_id, booked_at, status, pod_url, delivered_at, picked_up_at, cancelled_at, cancellation_reason, cancelled_by, agreed_rate_per_mile) VALUES ('BK-HIST-0016', 'LD-HIST-0016', 'drv-001', '2026-09-09 18:30:16.595462+05:45', 'completed', NULL, '2026-09-08 18:02:47.519+05:45', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.bookings (id, load_id, driver_id, booked_at, status, pod_url, delivered_at, picked_up_at, cancelled_at, cancellation_reason, cancelled_by, agreed_rate_per_mile) VALUES ('BK-HIST-0017', 'LD-HIST-0017', 'drv-001', '2026-09-09 18:30:16.595462+05:45', 'completed', NULL, '2026-09-09 06:13:04.222+05:45', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.bookings (id, load_id, driver_id, booked_at, status, pod_url, delivered_at, picked_up_at, cancelled_at, cancellation_reason, cancelled_by, agreed_rate_per_mile) VALUES ('BK-HIST-0018', 'LD-HIST-0018', 'drv-001', '2026-09-09 18:30:16.595462+05:45', 'completed', NULL, '2026-09-09 18:02:20.713+05:45', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.bookings (id, load_id, driver_id, booked_at, status, pod_url, delivered_at, picked_up_at, cancelled_at, cancellation_reason, cancelled_by, agreed_rate_per_mile) VALUES ('BK-QZ_5yJ-UL8Gj', 'LD-1043', 'drv-001', '2026-09-09 20:43:04.973634+05:45', 'completed', '/uploads/pod.png', '2026-09-09 20:43:05.051+05:45', NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.bookings (id, load_id, driver_id, booked_at, status, pod_url, delivered_at, picked_up_at, cancelled_at, cancellation_reason, cancelled_by, agreed_rate_per_mile) VALUES ('BK-VVjRBu-MiV8K', 'LD-1044', 'drv-002', '2026-09-09 20:44:02.05395+05:45', 'active', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.bookings (id, load_id, driver_id, booked_at, status, pod_url, delivered_at, picked_up_at, cancelled_at, cancellation_reason, cancelled_by, agreed_rate_per_mile) VALUES ('BK-9Xj5sNlMwJmw', 'LD-1045', 'drv-002', '2026-09-09 20:44:41.275833+05:45', 'active', NULL, NULL, NULL, NULL, NULL, NULL, NULL);


--
-- Data for Name: driver_documents; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: driver_equipment; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.driver_equipment (id, driver_id, equipment_type, trailer_length_ft) VALUES ('eq-drv-001', 'drv-001', 'dry_van', 53);
INSERT INTO public.driver_equipment (id, driver_id, equipment_type, trailer_length_ft) VALUES ('eq-drv-002', 'drv-002', 'reefer', 53);
INSERT INTO public.driver_equipment (id, driver_id, equipment_type, trailer_length_ft) VALUES ('eq-drv-wI2aqzVEQH-x', 'drv-wI2aqzVEQH-x', 'reefer', 53);
INSERT INTO public.driver_equipment (id, driver_id, equipment_type, trailer_length_ft) VALUES ('eq-drv-E3c4Jcvw0Ygw', 'drv-E3c4Jcvw0Ygw', 'dry_van', 53);
INSERT INTO public.driver_equipment (id, driver_id, equipment_type, trailer_length_ft) VALUES ('eq-drv-y-6Ted4ji-4G', 'drv-y-6Ted4ji-4G', 'reefer', 53);
INSERT INTO public.driver_equipment (id, driver_id, equipment_type, trailer_length_ft) VALUES ('eq-drv-dgfO2s6by-3q', 'drv-dgfO2s6by-3q', 'dry_van', 53);


--
-- Data for Name: driver_payment_accounts; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.driver_payment_accounts (id, driver_id, payment_processor, processor_account_id, same_day_funding_opt_in, created_at) VALUES ('pay-drv-001', 'drv-001', 'stripe_connect', 'acct_stripe_dr1_tokenized', true, '2026-09-09 18:30:16.595462+05:45');
INSERT INTO public.driver_payment_accounts (id, driver_id, payment_processor, processor_account_id, same_day_funding_opt_in, created_at) VALUES ('pay-drv-002', 'drv-002', 'stripe_connect', 'acct_stripe_dr2_tokenized', true, '2026-09-09 18:30:16.595462+05:45');
INSERT INTO public.driver_payment_accounts (id, driver_id, payment_processor, processor_account_id, same_day_funding_opt_in, created_at) VALUES ('pay-drv-wI2aqzVEQH-x', 'drv-wI2aqzVEQH-x', 'stripe_connect', 'acct_stripe_connect_8f3ada744260c4d7fd5115e8c31fbf63', true, '2026-09-09 20:43:25.134065+05:45');
INSERT INTO public.driver_payment_accounts (id, driver_id, payment_processor, processor_account_id, same_day_funding_opt_in, created_at) VALUES ('pay-drv-E3c4Jcvw0Ygw', 'drv-E3c4Jcvw0Ygw', 'stripe_connect', 'acct_stripe_connect_e3194f004d9196907bae5c63c83c678f', true, '2026-09-10 08:31:15.269492+05:45');
INSERT INTO public.driver_payment_accounts (id, driver_id, payment_processor, processor_account_id, same_day_funding_opt_in, created_at) VALUES ('pay-drv-y-6Ted4ji-4G', 'drv-y-6Ted4ji-4G', 'stripe_connect', 'acct_stripe_connect_0a0ce40b5ba273aa251a2de139c46813', true, '2026-09-10 08:31:30.300483+05:45');
INSERT INTO public.driver_payment_accounts (id, driver_id, payment_processor, processor_account_id, same_day_funding_opt_in, created_at) VALUES ('pay-drv-dgfO2s6by-3q', 'drv-dgfO2s6by-3q', 'stripe_connect', 'acct_stripe_connect_ffabb2b5f3d5f049199f985011b95c94', true, '2026-09-10 08:33:11.987873+05:45');


--
-- Data for Name: idempotency_keys; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: load_events; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: load_offers; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: notification_preferences; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.notification_preferences (user_id, booking_alerts, offer_alerts, settlement_alerts, verification_alerts, dispute_alerts, updated_at) VALUES ('usr-admin-1', true, true, true, true, true, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.notification_preferences (user_id, booking_alerts, offer_alerts, settlement_alerts, verification_alerts, dispute_alerts, updated_at) VALUES ('usr-shipper-1', true, true, true, true, true, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.notification_preferences (user_id, booking_alerts, offer_alerts, settlement_alerts, verification_alerts, dispute_alerts, updated_at) VALUES ('usr-driver-1', true, true, true, true, true, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.notification_preferences (user_id, booking_alerts, offer_alerts, settlement_alerts, verification_alerts, dispute_alerts, updated_at) VALUES ('usr-driver-2', true, true, true, true, true, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.notification_preferences (user_id, booking_alerts, offer_alerts, settlement_alerts, verification_alerts, dispute_alerts, updated_at) VALUES ('usr-qJ705CJD_XXZ', true, true, true, true, true, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.notification_preferences (user_id, booking_alerts, offer_alerts, settlement_alerts, verification_alerts, dispute_alerts, updated_at) VALUES ('usr-UBVnwhupvrVL', true, true, true, true, true, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.notification_preferences (user_id, booking_alerts, offer_alerts, settlement_alerts, verification_alerts, dispute_alerts, updated_at) VALUES ('usr-TUkIkFbOg6pG', true, true, true, true, true, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.notification_preferences (user_id, booking_alerts, offer_alerts, settlement_alerts, verification_alerts, dispute_alerts, updated_at) VALUES ('usr-JU2XzwDN3L0J', true, true, true, true, true, '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.notification_preferences (user_id, booking_alerts, offer_alerts, settlement_alerts, verification_alerts, dispute_alerts, updated_at) VALUES ('usr-YVkHDl4yaIK7', true, true, true, true, true, '2026-09-10 13:37:28.255315+05:45');


--
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: password_reset_tokens; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: platform_config; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.platform_config (key, value, updated_at) VALUES ('fee_pct', 0.05, '2026-09-09 18:30:15.338885+05:45');
INSERT INTO public.platform_config (key, value, updated_at) VALUES ('factor_pct', 0.03, '2026-09-09 18:30:15.338885+05:45');
INSERT INTO public.platform_config (key, value, updated_at) VALUES ('broker_comparison_pct', 0.20, '2026-09-09 18:30:15.338885+05:45');
INSERT INTO public.platform_config (key, value, updated_at) VALUES ('fuel_rate_per_mile', 0.45, '2026-09-09 18:30:15.338885+05:45');
INSERT INTO public.platform_config (key, value, updated_at) VALUES ('require_driver_verification', 0, '2026-09-10 13:37:28.255315+05:45');


--
-- Data for Name: ratings; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: refresh_tokens; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: schema_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.schema_migrations (version, checksum, applied_at) VALUES ('0001_initial_schema', 'bcc4d8c437bd48a7', '2026-09-09 18:30:15.338885+05:45');
INSERT INTO public.schema_migrations (version, checksum, applied_at) VALUES ('0002_security', '7320984253c94eb6', '2026-09-09 20:40:56.371881+05:45');
INSERT INTO public.schema_migrations (version, checksum, applied_at) VALUES ('0003_public_shipper_view', '7a12abfb908a27a6', '2026-09-09 20:42:13.294343+05:45');
INSERT INTO public.schema_migrations (version, checksum, applied_at) VALUES ('0004_load_claim_policy', '362270a38ae8bf90', '2026-09-09 20:43:01.763569+05:45');
INSERT INTO public.schema_migrations (version, checksum, applied_at) VALUES ('0005_onboarding_identity', '30c50dac89d25e3b', '2026-09-10 08:30:48.484771+05:45');
INSERT INTO public.schema_migrations (version, checksum, applied_at) VALUES ('0006_api_operations', 'fcd42f2e2d5e57ec', '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.schema_migrations (version, checksum, applied_at) VALUES ('0007_load_lifecycle', 'e5a87606523a95fe', '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.schema_migrations (version, checksum, applied_at) VALUES ('0008_offers', '40fe8cde1fd16408', '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.schema_migrations (version, checksum, applied_at) VALUES ('0009_reputation_and_notifications', 'ea501830058e259f', '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.schema_migrations (version, checksum, applied_at) VALUES ('0010_verification_and_disputes', '5bf44a055765df04', '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.schema_migrations (version, checksum, applied_at) VALUES ('0011_analytics', 'b6a41a42dbc1ae6d', '2026-09-10 13:37:28.255315+05:45');
INSERT INTO public.schema_migrations (version, checksum, applied_at) VALUES ('0012_admin_provisioning', 'ea12ead32500fd91', '2026-09-10 14:03:18.848941+05:45');


--
-- Data for Name: settlements; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.settlements (id, booking_id, load_id, miles, rate_per_mile, fuel_rate_per_mile, gross_amount, fee_amount, fee_pct_applied, fuel_cost, factor_cost, factored, net_amount, settled_at) VALUES ('STL-00001', 'BK-HIST-0001', 'LD-HIST-0001', 780, 2.42, 0.45, 1887.6, 94.38, 0.05, 351, 0, false, 1442.2199999999998, '2026-09-01 05:52:31.524+05:45');
INSERT INTO public.settlements (id, booking_id, load_id, miles, rate_per_mile, fuel_rate_per_mile, gross_amount, fee_amount, fee_pct_applied, fuel_cost, factor_cost, factored, net_amount, settled_at) VALUES ('STL-00002', 'BK-HIST-0002', 'LD-HIST-0002', 530, 2.09, 0.45, 1107.6999999999998, 55.38499999999999, 0.05, 238.5, 0, false, 813.8149999999998, '2026-09-01 17:38:33.453+05:45');
INSERT INTO public.settlements (id, booking_id, load_id, miles, rate_per_mile, fuel_rate_per_mile, gross_amount, fee_amount, fee_pct_applied, fuel_cost, factor_cost, factored, net_amount, settled_at) VALUES ('STL-00003', 'BK-HIST-0003', 'LD-HIST-0003', 370, 2.91, 0.45, 1076.7, 53.83500000000001, 0.05, 166.5, 32.301, true, 824.064, '2026-09-02 05:48:28.146+05:45');
INSERT INTO public.settlements (id, booking_id, load_id, miles, rate_per_mile, fuel_rate_per_mile, gross_amount, fee_amount, fee_pct_applied, fuel_cost, factor_cost, factored, net_amount, settled_at) VALUES ('STL-00004', 'BK-HIST-0004', 'LD-HIST-0004', 1240, 2.74, 0.45, 3397.6000000000004, 169.88000000000002, 0.05, 558, 0, false, 2669.7200000000003, '2026-09-02 17:31:55.521+05:45');
INSERT INTO public.settlements (id, booking_id, load_id, miles, rate_per_mile, fuel_rate_per_mile, gross_amount, fee_amount, fee_pct_applied, fuel_cost, factor_cost, factored, net_amount, settled_at) VALUES ('STL-00005', 'BK-HIST-0005', 'LD-HIST-0005', 650, 2.25, 0.45, 1462.5, 73.125, 0.05, 292.5, 0, false, 1096.875, '2026-09-03 05:39:46.822+05:45');
INSERT INTO public.settlements (id, booking_id, load_id, miles, rate_per_mile, fuel_rate_per_mile, gross_amount, fee_amount, fee_pct_applied, fuel_cost, factor_cost, factored, net_amount, settled_at) VALUES ('STL-00006', 'BK-HIST-0006', 'LD-HIST-0006', 530, 2.85, 0.45, 1510.5, 75.525, 0.05, 238.5, 45.315, true, 1151.1599999999999, '2026-09-03 18:15:16.858+05:45');
INSERT INTO public.settlements (id, booking_id, load_id, miles, rate_per_mile, fuel_rate_per_mile, gross_amount, fee_amount, fee_pct_applied, fuel_cost, factor_cost, factored, net_amount, settled_at) VALUES ('STL-00007', 'BK-HIST-0007', 'LD-HIST-0007', 1020, 2.63, 0.45, 2682.6, 134.13, 0.05, 459, 0, false, 2089.47, '2026-09-04 06:02:34.778+05:45');
INSERT INTO public.settlements (id, booking_id, load_id, miles, rate_per_mile, fuel_rate_per_mile, gross_amount, fee_amount, fee_pct_applied, fuel_cost, factor_cost, factored, net_amount, settled_at) VALUES ('STL-00008', 'BK-HIST-0008', 'LD-HIST-0008', 780, 3.11, 0.45, 2425.7999999999997, 121.28999999999999, 0.05, 351, 0, false, 1953.5099999999998, '2026-09-04 18:06:48.652+05:45');
INSERT INTO public.settlements (id, booking_id, load_id, miles, rate_per_mile, fuel_rate_per_mile, gross_amount, fee_amount, fee_pct_applied, fuel_cost, factor_cost, factored, net_amount, settled_at) VALUES ('STL-00009', 'BK-HIST-0009', 'LD-HIST-0009', 490, 2.48, 0.45, 1215.2, 60.760000000000005, 0.05, 220.5, 36.456, true, 897.484, '2026-09-05 05:30:49.889+05:45');
INSERT INTO public.settlements (id, booking_id, load_id, miles, rate_per_mile, fuel_rate_per_mile, gross_amount, fee_amount, fee_pct_applied, fuel_cost, factor_cost, factored, net_amount, settled_at) VALUES ('STL-00010', 'BK-HIST-0010', 'LD-HIST-0010', 260, 3.14, 0.45, 816.4, 40.82, 0.05, 117, 0, false, 658.5799999999999, '2026-09-05 17:53:54.84+05:45');
INSERT INTO public.settlements (id, booking_id, load_id, miles, rate_per_mile, fuel_rate_per_mile, gross_amount, fee_amount, fee_pct_applied, fuel_cost, factor_cost, factored, net_amount, settled_at) VALUES ('STL-00011', 'BK-HIST-0011', 'LD-HIST-0011', 700, 2.19, 0.45, 1533, 76.65, 0.05, 315, 0, false, 1141.35, '2026-09-06 05:33:42.363+05:45');
INSERT INTO public.settlements (id, booking_id, load_id, miles, rate_per_mile, fuel_rate_per_mile, gross_amount, fee_amount, fee_pct_applied, fuel_cost, factor_cost, factored, net_amount, settled_at) VALUES ('STL-00012', 'BK-HIST-0012', 'LD-HIST-0012', 370, 2.08, 0.45, 769.6, 38.480000000000004, 0.05, 166.5, 23.088, true, 541.532, '2026-09-06 17:52:55.979+05:45');
INSERT INTO public.settlements (id, booking_id, load_id, miles, rate_per_mile, fuel_rate_per_mile, gross_amount, fee_amount, fee_pct_applied, fuel_cost, factor_cost, factored, net_amount, settled_at) VALUES ('STL-00013', 'BK-HIST-0013', 'LD-HIST-0013', 780, 3.08, 0.45, 2402.4, 120.12, 0.05, 351, 0, false, 1931.2800000000002, '2026-09-07 05:31:06.74+05:45');
INSERT INTO public.settlements (id, booking_id, load_id, miles, rate_per_mile, fuel_rate_per_mile, gross_amount, fee_amount, fee_pct_applied, fuel_cost, factor_cost, factored, net_amount, settled_at) VALUES ('STL-00014', 'BK-HIST-0014', 'LD-HIST-0014', 530, 2.78, 0.45, 1473.3999999999999, 73.67, 0.05, 238.5, 0, false, 1161.2299999999998, '2026-09-07 18:08:53.531+05:45');
INSERT INTO public.settlements (id, booking_id, load_id, miles, rate_per_mile, fuel_rate_per_mile, gross_amount, fee_amount, fee_pct_applied, fuel_cost, factor_cost, factored, net_amount, settled_at) VALUES ('STL-00015', 'BK-HIST-0015', 'LD-HIST-0015', 370, 2.68, 0.45, 991.6, 49.580000000000005, 0.05, 166.5, 29.748, true, 745.7719999999999, '2026-09-08 05:49:03.159+05:45');
INSERT INTO public.settlements (id, booking_id, load_id, miles, rate_per_mile, fuel_rate_per_mile, gross_amount, fee_amount, fee_pct_applied, fuel_cost, factor_cost, factored, net_amount, settled_at) VALUES ('STL-00016', 'BK-HIST-0016', 'LD-HIST-0016', 1240, 2.6, 0.45, 3224, 161.20000000000002, 0.05, 558, 0, false, 2504.8, '2026-09-08 18:02:47.519+05:45');
INSERT INTO public.settlements (id, booking_id, load_id, miles, rate_per_mile, fuel_rate_per_mile, gross_amount, fee_amount, fee_pct_applied, fuel_cost, factor_cost, factored, net_amount, settled_at) VALUES ('STL-00017', 'BK-HIST-0017', 'LD-HIST-0017', 650, 2.49, 0.45, 1618.5000000000002, 80.92500000000001, 0.05, 292.5, 0, false, 1245.0750000000003, '2026-09-09 06:13:04.222+05:45');
INSERT INTO public.settlements (id, booking_id, load_id, miles, rate_per_mile, fuel_rate_per_mile, gross_amount, fee_amount, fee_pct_applied, fuel_cost, factor_cost, factored, net_amount, settled_at) VALUES ('STL-00018', 'BK-HIST-0018', 'LD-HIST-0018', 530, 2.39, 0.45, 1266.7, 63.33500000000001, 0.05, 238.5, 38.001, true, 926.864, '2026-09-09 18:02:20.713+05:45');
INSERT INTO public.settlements (id, booking_id, load_id, miles, rate_per_mile, fuel_rate_per_mile, gross_amount, fee_amount, fee_pct_applied, fuel_cost, factor_cost, factored, net_amount, settled_at) VALUES ('STL-n1lovcowNFQ6', 'BK-QZ_5yJ-UL8Gj', 'LD-1043', 530, 2.45, 0.45, 1298.5, 64.925, 0.05, 238.5, 38.955, true, 956.12, '2026-09-09 20:43:05.051+05:45');


--
-- Data for Name: settlement_disputes; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: settlement_adjustments; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: verification_reviews; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Name: audit_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.audit_log_id_seq', 56, true);


--
-- Name: auth_login_attempts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_login_attempts_id_seq', 19, true);


--
-- PostgreSQL database dump complete
--


