--
-- America Ships On Click — Roles & privileges
--
-- Runtime role and its grants. Load after database/sql/schema.sql; RLS policies are already in that file.
--
-- Generated by database/scripts/export-sql.sh from a live database.
-- Target: PostgreSQL 12+
--
-- Load with:
--   psql "$DATABASE_URL" -f database/sql/security.sql
--
-- Or paste into any SQL console (Supabase, pgAdmin, Neon, RDS Query Editor).
--

-- The runtime role. Created without LOGIN: grant login and set a password out
-- of band (scripts/postgres-dev.sh, or your provider's console), so no secret
-- ever lives in a dump file.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'asoc_app') THEN
    CREATE ROLE asoc_app NOLOGIN;
  END IF;
END $$;

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO asoc_app;
GRANT ALL ON FUNCTION public.app_accept_offer(p_offer_id text, p_note text) TO asoc_app;
GRANT ALL ON FUNCTION public.app_change_password(p_user_id text, p_new_hash text) TO asoc_app;
GRANT ALL ON FUNCTION public.app_consume_refresh_token(p_token_hash text) TO asoc_app;
GRANT ALL ON FUNCTION public.app_create_password_reset(p_email text, p_token_hash text, p_ttl_minutes integer, p_ip text) TO asoc_app;
GRANT ALL ON FUNCTION public.app_current_driver_id() TO asoc_app;
GRANT ALL ON FUNCTION public.app_current_role() TO asoc_app;
GRANT ALL ON FUNCTION public.app_current_shipper_id() TO asoc_app;
GRANT ALL ON FUNCTION public.app_current_user_id() TO asoc_app;
GRANT ALL ON FUNCTION public.app_expire_stale_offers() TO asoc_app;
GRANT ALL ON FUNCTION public.app_idempotency_begin(p_key text, p_user_id text, p_endpoint text, p_request_hash text) TO asoc_app;
GRANT ALL ON FUNCTION public.app_idempotency_complete(p_key text, p_user_id text, p_endpoint text, p_status integer, p_body jsonb) TO asoc_app;
GRANT ALL ON FUNCTION public.app_idempotency_release(p_key text, p_user_id text, p_endpoint text) TO asoc_app;
GRANT ALL ON FUNCTION public.app_is_admin() TO asoc_app;
GRANT ALL ON FUNCTION public.app_issue_refresh_token(p_user_id text, p_token_hash text, p_ttl_days integer, p_family_id text, p_user_agent text, p_ip text) TO asoc_app;
GRANT ALL ON FUNCTION public.app_list_sessions(p_user_id text) TO asoc_app;
GRANT ALL ON FUNCTION public.app_log_load_event(p_load_id text, p_booking_id text, p_type public.load_event_type, p_from text, p_to text, p_notes text, p_city text, p_state text, p_metadata jsonb) TO asoc_app;
GRANT ALL ON FUNCTION public.app_login_lockout_seconds(p_email text) TO asoc_app;
GRANT ALL ON FUNCTION public.app_notify(p_user_id text, p_type text, p_title text, p_body text, p_link text, p_load_id text, p_severity text) TO asoc_app;
GRANT ALL ON FUNCTION public.app_rate_limit_hit(p_bucket text, p_limit integer, p_window_secs integer) TO asoc_app;
GRANT ALL ON FUNCTION public.app_record_login_attempt(p_email text, p_ip text, p_ok boolean) TO asoc_app;
GRANT ALL ON FUNCTION public.app_reset_password(p_token_hash text, p_new_hash text) TO asoc_app;
GRANT ALL ON FUNCTION public.app_resolve_dispute(p_dispute_id text, p_status public.dispute_status, p_note text, p_adjustment numeric) TO asoc_app;
GRANT ALL ON FUNCTION public.app_review_driver_document(p_document_id text, p_decision public.verification_status, p_notes text) TO asoc_app;
GRANT ALL ON FUNCTION public.app_revoke_refresh_token(p_token_hash text, p_reason text) TO asoc_app;
GRANT ALL ON FUNCTION public.app_revoke_user_sessions(p_user_id text, p_reason text) TO asoc_app;
GRANT ALL ON FUNCTION public.app_set_driver_verification(p_driver_id text, p_status public.verification_status, p_reason text) TO asoc_app;
GRANT SELECT,INSERT,UPDATE ON TABLE public.bookings TO asoc_app;
GRANT SELECT,INSERT ON TABLE public.driver_documents TO asoc_app;
GRANT SELECT,INSERT,UPDATE ON TABLE public.driver_profiles TO asoc_app;
GRANT SELECT ON TABLE public.settlement_adjustments TO asoc_app;
GRANT SELECT,INSERT ON TABLE public.settlements TO asoc_app;
GRANT SELECT ON TABLE public.driver_earnings_view TO asoc_app;
GRANT SELECT,INSERT,UPDATE ON TABLE public.driver_equipment TO asoc_app;
GRANT SELECT,INSERT,UPDATE ON TABLE public.driver_payment_accounts TO asoc_app;
GRANT SELECT ON TABLE public.driver_performance_view TO asoc_app;
GRANT SELECT,INSERT,UPDATE ON TABLE public.ratings TO asoc_app;
GRANT SELECT ON TABLE public.driver_reputation_view TO asoc_app;
GRANT SELECT,INSERT,UPDATE ON TABLE public.loads TO asoc_app;
GRANT SELECT ON TABLE public.lane_rate_stats_view TO asoc_app;
GRANT SELECT ON TABLE public.load_board_stats_view TO asoc_app;
GRANT SELECT ON TABLE public.load_events TO asoc_app;
GRANT SELECT,INSERT,UPDATE ON TABLE public.load_offers TO asoc_app;
GRANT SELECT,INSERT,UPDATE ON TABLE public.notification_preferences TO asoc_app;
GRANT SELECT,UPDATE ON TABLE public.notifications TO asoc_app;
GRANT SELECT ON TABLE public.platform_config TO asoc_app;
GRANT SELECT ON TABLE public.public_ledger_view TO asoc_app;
GRANT SELECT,INSERT ON TABLE public.shipper_profiles TO asoc_app;
GRANT SELECT ON TABLE public.public_shipper_view TO asoc_app;
GRANT SELECT ON TABLE public.schema_migrations TO asoc_app;
GRANT SELECT,INSERT ON TABLE public.settlement_disputes TO asoc_app;
GRANT SELECT ON TABLE public.settlement_effective_view TO asoc_app;
GRANT SELECT ON TABLE public.settlement_totals_view TO asoc_app;
GRANT SELECT ON TABLE public.shipper_reputation_view TO asoc_app;
GRANT SELECT ON TABLE public.shipper_spend_view TO asoc_app;
GRANT SELECT,INSERT ON TABLE public.users TO asoc_app;
GRANT SELECT ON TABLE public.verification_reviews TO asoc_app;
