#!/usr/bin/env bash
#
# Exports the database as portable .sql files into database/sql/.
#
#   database/sql/schema.sql    structure only  — enums, tables, constraints, views, indexes
#   database/sql/data.sql      rows only       — portable INSERT statements
#   database/sql/database.sql  schema + data   — one file that rebuilds everything
#
# Dumps whatever DATABASE_ADMIN_URL points at, falling back to DATABASE_URL
# (both read from .env when not already set).
#
#   ./database/scripts/export-sql.sh
#
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT_DIR="$PROJECT_ROOT/database/sql"

# Dump as the owner, not as the runtime role.
#
# DATABASE_URL is the least-privilege application role: it cannot read
# audit_log, and pg_dump takes an ACCESS SHARE lock on every table before it
# reads anything, so the dump dies on the first denied table — after the output
# file has already been opened and truncated. DATABASE_ADMIN_URL is the same
# owner connection migrations and seeding use, and it is the only one that can
# see the whole schema. Fall back to DATABASE_URL for setups that define no
# separate owner connection.
env_value() {
  [ -f "$PROJECT_ROOT/.env" ] || return 0
  grep -E "^[[:space:]]*$1=" "$PROJECT_ROOT/.env" | tail -1 |
    sed -E 's/^[^=]+=//; s/^"//; s/"$//'
}

: "${DATABASE_ADMIN_URL:=$(env_value DATABASE_ADMIN_URL)}"
: "${DATABASE_URL:=$(env_value DATABASE_URL)}"

DUMP_URL="${DATABASE_ADMIN_URL:-${DATABASE_URL:-}}"

if [ -z "$DUMP_URL" ]; then
  echo "error: neither DATABASE_ADMIN_URL nor DATABASE_URL is set, and no .env file defines them." >&2
  echo "       These exports come from a live PostgreSQL server — start one with 'npm run db:up'." >&2
  exit 1
fi

if [ -z "${DATABASE_ADMIN_URL:-}" ]; then
  echo "warning: DATABASE_ADMIN_URL is not set; dumping as DATABASE_URL." >&2
  echo "         If that role is the least-privilege application role, the dump will fail" >&2
  echo "         on tables it cannot read (audit_log)." >&2
fi

find_pg_bin() {
  if [ -n "${PGBIN:-}" ]; then echo "$PGBIN"; return; fi
  local candidate
  candidate="$(ls -d /usr/lib/postgresql/*/bin /opt/homebrew/opt/postgresql@*/bin \
    /usr/local/opt/postgresql@*/bin /usr/pgsql-*/bin 2>/dev/null | sort -V | tail -1)"
  if [ -n "$candidate" ]; then echo "$candidate"; return; fi
  if command -v pg_dump >/dev/null 2>&1; then dirname "$(command -v pg_dump)"; return; fi
  echo ""
}

PG_BIN="$(find_pg_bin)"
if [ -z "$PG_BIN" ]; then
  echo "error: pg_dump not found. Install the PostgreSQL client tools, or set PGBIN." >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

# --column-inserts emits one INSERT per row with explicit column names, so the
# data loads into any PostgreSQL server regardless of column order — unlike the
# default COPY blocks, which are position-dependent.
COMMON_FLAGS=(--no-owner --no-privileges --no-tablespaces)

# pg_dump 16.10+ wraps its output in \restrict / \unrestrict psql meta-commands.
# psql understands them; Supabase's SQL editor, pgAdmin's query tool, and every
# driver-based import do not — they fail with a syntax error on line 1. Strip
# them so these files are pure SQL that runs anywhere.
dump() {
  "$PG_BIN/pg_dump" "$DUMP_URL" "$@" "${COMMON_FLAGS[@]}" |
    sed '/^\\restrict /d; /^\\unrestrict /d'
}

header() {
  cat <<EOF
--
-- America Ships On Click — $1
--
-- $2
--
-- Generated by database/scripts/export-sql.sh from a live database.
-- Target: PostgreSQL 12+
--
-- Load with:
--   psql "\$DATABASE_URL" -f database/sql/$3
--
-- Or paste into any SQL console (Supabase, pgAdmin, Neon, RDS Query Editor).
--

EOF
}

echo "Dumping schema..."
{
  header "Schema" "Structure only: enums, tables, constraints, views, and indexes. No rows." "schema.sql"
  dump --schema-only
} > "$OUT_DIR/schema.sql"

echo "Dumping data..."
{
  header "Data" "Rows only: demo accounts, loads, bookings, settlements, and platform config. Load database/sql/schema.sql first." "data.sql"
  dump --data-only --column-inserts
} > "$OUT_DIR/data.sql"

echo "Writing combined dump..."
{
  header "Complete database" "Schema and data in one file — rebuilds the entire database from scratch." "database.sql"
  dump --column-inserts
} > "$OUT_DIR/database.sql"

echo "Writing privileges..."
# The portable dumps above are privilege-free so they load into any database,
# under any role name. The access-control layer is emitted separately: role,
# GRANTs, and REVOKEs. RLS policies themselves travel with schema.sql.
{
  header "Roles & privileges" "Runtime role and its grants. Load after database/sql/schema.sql; RLS policies are already in that file." "security.sql"
  cat <<'ROLE_SQL'
-- The runtime role. Created without LOGIN: grant login and set a password out
-- of band (scripts/postgres-dev.sh, or your provider's console), so no secret
-- ever lives in a dump file.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'asoc_app') THEN
    CREATE ROLE asoc_app NOLOGIN;
  END IF;
END $$;

ROLE_SQL
  "$PG_BIN/pg_dump" "$DUMP_URL" --schema-only --no-owner --no-tablespaces |
    sed '/^\\restrict /d; /^\\unrestrict /d' |
    grep -E '^(GRANT|REVOKE) ' || true
} > "$OUT_DIR/security.sql"

echo
for file in schema.sql data.sql security.sql database.sql; do
  printf '  database/sql/%-14s %6s lines  %s\n' "$file" \
    "$(wc -l < "$OUT_DIR/$file")" "$(du -h "$OUT_DIR/$file" | cut -f1)"
done
